version: '3.8'
services:
  redis:
    image: "redis:alpine"
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local